routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /offline/: offline
  /recommendations/:
    template: recommend
    # data: page.recommendations # When active data will be taken from the  "/recommendations/" page

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
